import { Building2, Check, KeyRound, MapPin, Moon, Sun, UserRound } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import type { Account, OrganizationNameChangeRequest } from '@bloom/contracts';
import { api } from '../api';
import { Field, Notice } from '../components';

export function AccountSettings({ account, onAccountChanged }: { account: Account; onAccountChanged: (account: Account) => void }) {
  const [dark, setDark] = useState(() => localStorage.getItem('bloom_theme') === 'dark');
  const [holderName, setHolderName] = useState(account.displayName); const [holderBusy, setHolderBusy] = useState(false); const [holderMessage, setHolderMessage] = useState('');
  const [nameRequest, setNameRequest] = useState<OrganizationNameChangeRequest | null>(null); const [requestedName, setRequestedName] = useState(''); const [nameReason, setNameReason] = useState(''); const [nameBusy, setNameBusy] = useState(false); const [nameMessage, setNameMessage] = useState('');
  const [currentPassphrase, setCurrentPassphrase] = useState(''); const [newPassphrase, setNewPassphrase] = useState(''); const [repeatPassphrase, setRepeatPassphrase] = useState(''); const [passBusy, setPassBusy] = useState(false); const [passMessage, setPassMessage] = useState(''); const [passError, setPassError] = useState('');
  const [location, setLocation] = useState({ locality: account.locality ?? '', collectionAddress: account.collectionAddress ?? '', collectionInstructions: account.collectionInstructions ?? '' }); const [locationBusy, setLocationBusy] = useState(false); const [locationMessage, setLocationMessage] = useState('');

  useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light'; localStorage.setItem('bloom_theme', dark ? 'dark' : 'light'); }, [dark]);
  useEffect(() => { api<OrganizationNameChangeRequest | null>('/account/organization-name-request').then(setNameRequest).catch(() => setNameRequest(null)); }, []);
  const saveHolder = async (event: FormEvent) => { event.preventDefault(); setHolderBusy(true); setHolderMessage(''); try { const updated = await api<Account>('/account/profile', { method: 'PATCH', body: JSON.stringify({ displayName: holderName }) }); onAccountChanged(updated); setHolderMessage('Account holder updated.'); } catch (reason) { setHolderMessage(reason instanceof Error ? reason.message : 'The account holder could not be updated.'); } finally { setHolderBusy(false); } };
  const saveLocation = async (event: FormEvent) => { event.preventDefault(); setLocationBusy(true); setLocationMessage(''); try { const updated = await api<Account>('/account/collection-profile', { method: 'PATCH', body: JSON.stringify(location) }); onAccountChanged(updated); setLocationMessage('Collection details updated.'); } catch (reason) { setLocationMessage(reason instanceof Error ? reason.message : 'Collection details could not be updated.'); } finally { setLocationBusy(false); } };
  const requestName = async (event: FormEvent) => { event.preventDefault(); setNameBusy(true); setNameMessage(''); try { const created = await api<OrganizationNameChangeRequest>('/account/organization-name-request', { method: 'POST', body: JSON.stringify({ requestedName, reason: nameReason }) }); setNameRequest(created); setRequestedName(''); setNameReason(''); setNameMessage('Organization name change requested.'); } catch (reason) { setNameMessage(reason instanceof Error ? reason.message : 'The organization name request could not be sent.'); } finally { setNameBusy(false); } };
  const changePassphrase = async (event: FormEvent) => { event.preventDefault(); setPassError(''); setPassMessage(''); if (newPassphrase !== repeatPassphrase) { setPassError('The new passphrases do not match.'); return; } setPassBusy(true); try { await api('/account/change-passphrase', { method: 'POST', body: JSON.stringify({ currentPassphrase, newPassphrase }) }); setCurrentPassphrase(''); setNewPassphrase(''); setRepeatPassphrase(''); setPassMessage('Passphrase changed.'); } catch (reason) { setPassError(reason instanceof Error ? reason.message : 'The passphrase could not be changed.'); } finally { setPassBusy(false); } };

  return <main className="page settings-page self-settings"><section className="page-heading"><div><p className="eyebrow">Organization workspace</p><h1>Settings</h1><p>Manage your account and workspace preferences.</p></div></section><div className="self-settings__grid">
    <section className="settings-card self-setting-card"><header><span><UserRound size={21} /></span><div><p className="eyebrow">Profile</p><h2>Account holder</h2></div></header><form onSubmit={saveHolder}><Field label="Account holder name"><input value={holderName} onChange={(event) => setHolderName(event.target.value)} minLength={2} maxLength={80} required /></Field><Field label="Email or phone" hint="Contact changes will become available after verification is configured."><input value={account.contact || 'No contact recorded'} disabled /></Field>{holderMessage && <Notice tone={holderMessage.endsWith('updated.') ? 'success' : 'error'}>{holderMessage}</Notice>}<button className="button button--primary" disabled={holderBusy || holderName.trim() === account.displayName}>{holderBusy ? 'Saving…' : 'Save account holder'}</button></form></section>
    <section className="settings-card self-setting-card"><header><span><Building2 size={21} /></span><div><p className="eyebrow">Organization</p><h2>Registered name</h2></div></header>{account.organizationTypeName && <div className="organization-category"><span>Food Waste Producer category</span><strong>{account.organizationTypeName}</strong></div>}{nameRequest ? <div className="pending-name"><span><Check size={18} /></span><div><p className="eyebrow">Awaiting administrator review</p><h3>{nameRequest.requestedName}</h3><p>Your workspace continues to use <strong>{account.organizationName}</strong> until approved.</p></div></div> : <form onSubmit={requestName}><Field label="Current organization name"><input value={account.organizationName} disabled /></Field><Field label="Requested organization name"><input value={requestedName} onChange={(event) => setRequestedName(event.target.value)} minLength={2} maxLength={120} placeholder="Enter the updated registered name" required /></Field><Field label="Reason (optional)"><textarea rows={2} value={nameReason} onChange={(event) => setNameReason(event.target.value)} maxLength={300} /></Field>{nameMessage && <Notice tone={nameMessage.endsWith('requested.') ? 'success' : 'error'}>{nameMessage}</Notice>}<button className="button button--primary" disabled={nameBusy || requestedName.trim().length < 2}>{nameBusy ? 'Sending…' : 'Request name change'}</button></form>}</section>
    {account.role === 'FOOD_WASTE_PRODUCER' && <section className="settings-card self-setting-card collection-profile-card"><header><span><MapPin size={21} /></span><div><p className="eyebrow">Pickup location</p><h2>Collection details</h2></div></header><p className="settings-card__intro">These details are copied onto each pickup, so active listings never change unexpectedly.</p><form onSubmit={saveLocation}><Field label="Locality"><input value={location.locality} onChange={(event) => setLocation({ ...location, locality: event.target.value })} minLength={2} maxLength={100} required /></Field><Field label="Full collection address"><textarea rows={3} value={location.collectionAddress} onChange={(event) => setLocation({ ...location, collectionAddress: event.target.value })} minLength={8} maxLength={240} required /></Field><Field label="Default collection instructions (optional)"><textarea rows={2} value={location.collectionInstructions} onChange={(event) => setLocation({ ...location, collectionInstructions: event.target.value })} maxLength={400} /></Field>{locationMessage && <Notice tone={locationMessage.endsWith('updated.') ? 'success' : 'error'}>{locationMessage}</Notice>}<button className="button button--primary" disabled={locationBusy}>{locationBusy ? 'Saving…' : 'Save collection details'}</button></form></section>}
    <section className="settings-card self-setting-card"><header><span><KeyRound size={21} /></span><div><p className="eyebrow">Security</p><h2>Passphrase</h2></div></header><form onSubmit={changePassphrase}><Field label="Current passphrase"><input type="password" autoComplete="current-password" value={currentPassphrase} onChange={(event) => setCurrentPassphrase(event.target.value)} required /></Field><div className="field-grid"><Field label="New passphrase"><input type="password" autoComplete="new-password" minLength={10} value={newPassphrase} onChange={(event) => setNewPassphrase(event.target.value)} required /></Field><Field label="Repeat new passphrase"><input type="password" autoComplete="new-password" minLength={10} value={repeatPassphrase} onChange={(event) => setRepeatPassphrase(event.target.value)} required /></Field></div>{passError && <Notice tone="error">{passError}</Notice>}{passMessage && <Notice tone="success">{passMessage}</Notice>}<button className="button button--primary" disabled={passBusy || newPassphrase.length < 10}>{passBusy ? 'Changing…' : 'Change passphrase'}</button></form></section>
    <section className="settings-card self-setting-card appearance-card"><header><span>{dark ? <Moon size={21} /> : <Sun size={21} />}</span><div><p className="eyebrow">Display</p><h2>Appearance</h2></div></header><button className="theme-choice" onClick={() => setDark((value) => !value)}><span>{dark ? <Moon size={24} /> : <Sun size={24} />}</span><div><strong>{dark ? 'Dark workspace' : 'Light workspace'}</strong><small>Use {dark ? 'light' : 'dark'} mode on this device</small></div><i className={dark ? 'on' : ''}><b /></i></button></section>
  </div></main>;
}
