import { ArrowRight, ClipboardCheck, Lightbulb, Pencil, Plus, Scale, Trash2, TrendingDown } from 'lucide-react';
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import type { Account, DailyWasteLog, InsightSummary, Pickup, ServicePeriod, WasteReason, WasteStage } from '@bloom/contracts';
import { api, formatDate } from '../api';
import { ConfirmDialog, Field, Notice, SelectField, Spinner } from '../components';

const serviceLabels: Record<ServicePeriod, string> = { BREAKFAST: 'Breakfast', LUNCH: 'Lunch', DINNER: 'Dinner', ALL_DAY: 'All day', EVENT: 'Event', OTHER: 'Other' };
const stageLabels: Record<WasteStage, string> = { PREPARATION: 'Preparation', STORAGE_SPOILAGE: 'Storage / spoilage', OVERPRODUCTION: 'Overproduction', PLATE_RETURN: 'Plate return', OTHER: 'Other' };
const reasons: Array<[WasteReason, string]> = [['LOW_DEMAND', 'Lower demand'], ['FORECAST_VARIANCE', 'Forecast variance'], ['CUSTOMER_PREFERENCE', 'Customer preference'], ['PORTION_SIZE', 'Portion size'], ['QUALITY_ISSUE', 'Quality issue'], ['PROCESS_ERROR', 'Process error'], ['OVERPRODUCTION', 'Overproduction'], ['PREPARATION_WASTE', 'Preparation waste'], ['OTHER', 'Other']];
const reasonLabel = (value: WasteReason) => reasons.find(([reason]) => reason === value)?.[1] ?? value.replaceAll('_', ' ').toLowerCase();
const localDateTime = (value = new Date()) => new Date(value.getTime() - value.getTimezoneOffset() * 60000).toISOString().slice(0, 16);
const lockedStatuses = ['RESERVED', 'IN_TRANSIT', 'AWAITING_PROVIDER_CONFIRMATION', 'COLLECTED'];

export function Dashboard({ account }: { account: Account }) {
  const [logs, setLogs] = useState<DailyWasteLog[]>([]); const [pickups, setPickups] = useState<Pickup[]>([]); const [insights, setInsights] = useState<InsightSummary | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editorOpen, setEditorOpen] = useState(false); const [editing, setEditing] = useState<DailyWasteLog | null>(null);
  const load = async (pageLoader = false) => { if (pageLoader) setLoading(true); setError(''); try { const [logBody, pickupBody, insightBody] = await Promise.all([api<{ data: DailyWasteLog[] }>('/waste-logs'), api<{ data: Pickup[] }>('/pickups'), api<InsightSummary>('/insights')]); setLogs(logBody.data); setPickups(pickupBody.data); setInsights(insightBody); } catch (reason) { setError(reason instanceof Error ? reason.message : 'The operations desk could not be loaded.'); } finally { setLoading(false); } };
  useEffect(() => { void load(true); }, []);
  const activePickups = pickups.filter((pickup) => !['COLLECTED', 'CANCELLED', 'EXPIRED'].includes(pickup.status));
  if (loading) return <main className="page"><Spinner label="Preparing the waste operations desk" /></main>;
  if (error && !insights) return <main className="page"><Notice tone="error"><span>{error}</span><button onClick={() => void load(true)}>Try again</button></Notice></main>;
  return <main className="page producer-ops">
    <header className="producer-ops__header"><div><div className="producer-identity"><span>Food Waste Producer</span>{account.organizationTypeName && <b>{account.organizationTypeName}</b>}</div><h1>{account.organizationName}</h1><p>Record what leaves the kitchen, see where it occurs, and prepare eligible waste for collection.</p></div><button className="button button--primary" onClick={() => { setEditing(null); setEditorOpen(true); }}><Plus size={17} /> Record waste</button></header>
    {error && <Notice tone="error">{error}</Notice>}
    <Kpis insights={insights!} activePickups={activePickups.length} />
    <div className="producer-ops__grid"><Records logs={logs} pickups={pickups} onEdit={(log) => { setEditing(log); setEditorOpen(true); }} onChanged={() => load()} /><Insights insights={insights!} /></div>
    <section className="producer-pickup-strip"><div><p className="eyebrow">Collection movement</p><h2>{activePickups.length ? `${activePickups.length} active pickup${activePickups.length === 1 ? '' : 's'}` : 'No active pickups'}</h2><p>{activePickups.length ? 'Track reservations and confirm completed collections from the pickup desk.' : 'Mark a suitable waste record and publish it when collection is needed.'}</p></div><Link className="button button--quiet" to="/pickups">Open pickups <ArrowRight size={16} /></Link></section>
    <WasteEditor open={editorOpen} log={editing} onClose={() => { setEditorOpen(false); setEditing(null); }} onSaved={async () => { setEditorOpen(false); setEditing(null); await load(); }} />
  </main>;
}

function Kpis({ insights, activePickups }: { insights: InsightSummary; activePickups: number }) {
  const change = insights.sevenDay.changePercent;
  const items = [['Waste recorded', `${insights.sevenDay.totalKg} kg`, 'Last 7 days'], ['Collection suitable', `${insights.sevenDay.collectionSuitableKg} kg`, 'Last 7 days'], ['Waste records', String(insights.sevenDay.recordCount), 'Last 7 days'], ['Change', change === null ? '—' : `${change > 0 ? '+' : ''}${change}%`, change === null ? 'Needs a prior week' : 'Versus previous 7 days'], ['Active pickups', String(activePickups), 'Awaiting completion']];
  return <section className="producer-kpis" aria-label="Seven day waste snapshot">{items.map(([label, value, note]) => <article key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</section>;
}

type WasteForm = { recordedAt: string; servicePeriod: ServicePeriod; wasteStage: WasteStage; foodCategory: string; leftoverKg: number; reason: WasteReason; suitableForCollection: boolean; notes: string };
const blankForm = (): WasteForm => ({ recordedAt: localDateTime(), servicePeriod: 'LUNCH', wasteStage: 'OVERPRODUCTION', foodCategory: '', leftoverKg: 0, reason: 'LOW_DEMAND', suitableForCollection: false, notes: '' });

function WasteEditor({ open, log, onClose, onSaved }: { open: boolean; log: DailyWasteLog | null; onClose: () => void; onSaved: () => Promise<void> }) {
  const [form, setForm] = useState<WasteForm>(blankForm); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (!open) return; setError(''); setForm(log ? { recordedAt: localDateTime(new Date(log.recordedAt ?? log.createdAt)), servicePeriod: log.servicePeriod ?? 'OTHER', wasteStage: log.wasteStage ?? 'OTHER', foodCategory: log.foodCategory ?? '', leftoverKg: log.leftoverKg, reason: log.reason, suitableForCollection: log.suitableForCollection, notes: log.notes } : blankForm()); }, [open, log]);
  if (!open) return null;
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await api(log ? `/waste-logs/${log.id}` : '/waste-logs', { method: log ? 'PUT' : 'POST', body: JSON.stringify({ ...form, recordedAt: new Date(form.recordedAt).toISOString() }) }); await onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'The waste record could not be saved.'); } finally { setBusy(false); } };
  return <div className="dialog-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) onClose(); }}><form className="dialog waste-editor" role="dialog" aria-modal="true" aria-labelledby="waste-editor-title" onSubmit={submit}><p className="eyebrow">Kitchen record</p><h2 id="waste-editor-title">{log ? 'Edit waste record' : 'Record food waste'}</h2><p>Use the figures measured after a service or kitchen process.</p>{error && <Notice tone="error">{error}</Notice>}<div className="field-grid"><Field label="Date and time"><input type="datetime-local" value={form.recordedAt} onChange={(event) => setForm({ ...form, recordedAt: event.target.value })} required /></Field><Field label="Service period"><SelectField value={form.servicePeriod} onChange={(event) => setForm({ ...form, servicePeriod: event.target.value as ServicePeriod })}>{Object.entries(serviceLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</SelectField></Field><Field label="Where waste occurred"><SelectField value={form.wasteStage} onChange={(event) => setForm({ ...form, wasteStage: event.target.value as WasteStage })}>{Object.entries(stageLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</SelectField></Field><Field label="Waste weight (kg)"><input type="number" min="0.1" max="500" step="0.1" value={form.leftoverKg || ''} onChange={(event) => setForm({ ...form, leftoverKg: Number(event.target.value) })} required /></Field><Field label="Primary cause"><SelectField value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value as WasteReason })}>{reasons.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</SelectField></Field><Field label="Food or category (optional)"><input value={form.foodCategory} maxLength={80} placeholder="e.g. rice, buffet salads" onChange={(event) => setForm({ ...form, foodCategory: event.target.value })} /></Field></div><Field label="Notes (optional)"><textarea rows={3} maxLength={500} value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></Field><label className="check-row"><input type="checkbox" checked={form.suitableForCollection} onChange={(event) => setForm({ ...form, suitableForCollection: event.target.checked })} /><span><strong>Suitable for collection</strong><small>This saves the record only. Publishing remains a separate decision.</small></span></label><div className="form-actions"><button type="button" className="button button--quiet" onClick={onClose}>Cancel</button><button className="button button--primary" disabled={busy || form.leftoverKg <= 0}>{busy ? 'Saving…' : 'Save record'}</button></div></form></div>;
}

function Records({ logs, pickups, onEdit, onChanged }: { logs: DailyWasteLog[]; pickups: Pickup[]; onEdit: (log: DailyWasteLog) => void; onChanged: () => Promise<void> }) {
  const [removing, setRemoving] = useState<DailyWasteLog | null>(null); const [publishing, setPublishing] = useState<DailyWasteLog | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const remove = async () => { if (!removing) return; setBusy(true); try { await api(`/waste-logs/${removing.id}`, { method: 'DELETE' }); setRemoving(null); await onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'The record could not be deleted.'); } finally { setBusy(false); } };
  return <section className="producer-panel producer-records"><header><div><p className="eyebrow">Operational record</p><h2>Recent waste</h2></div><span>{logs.length} total</span></header>{error && <Notice tone="error">{error}</Notice>}{logs.length ? <div className="waste-record-list">{logs.slice(0, 8).map((log) => { const pickup = pickups.find((item) => item.id === log.pickupId); const locked = Boolean(pickup && lockedStatuses.includes(pickup.status)); return <article key={log.id}><span className="record-stage"><Scale size={17} /></span><div><strong>{log.leftoverKg} kg</strong><p>{stageLabels[log.wasteStage ?? 'OTHER']} · {serviceLabels[log.servicePeriod ?? 'OTHER']}{log.foodCategory ? ` · ${log.foodCategory}` : ''}</p><small>{formatDate(log.recordedAt ?? log.createdAt, true)} · {reasonLabel(log.reason)}</small></div><div className="record-actions">{log.suitableForCollection && !log.pickupId && <button className="button button--compact publish-action" onClick={() => setPublishing(log)}><span aria-hidden="true">↗</span> Publish pickup</button>}{log.pickupId && <Link className="button button--compact button--quiet" to="/pickups">View pickup</Link>}<button className="icon-button" disabled={locked} onClick={() => onEdit(log)} aria-label="Edit waste record"><Pencil size={15} /></button><button className="icon-button icon-button--danger" disabled={locked} onClick={() => setRemoving(log)} aria-label="Delete waste record"><Trash2 size={15} /></button></div></article>; })}</div> : <div className="producer-empty"><span><ClipboardCheck size={22} /></span><h3>No waste has been recorded.</h3><p>Your seven-day snapshot and guidance will build from measured records.</p></div>}<ConfirmDialog open={Boolean(removing)} title="Delete this waste record?" description="This permanently removes the record and any pickup that has not been accepted." confirmLabel="Delete record" busy={busy} onConfirm={remove} onCancel={() => setRemoving(null)} /><PublishPickupDialog log={publishing} onClose={() => setPublishing(null)} onPublished={async () => { setPublishing(null); await onChanged(); }} /></section>;
}

function Insights({ insights }: { insights: InsightSummary }) {
  const chart = useMemo(() => { const max = Math.max(...insights.trend.map((item) => item.leftoverKg), 1); const points = insights.trend.map((item, index) => ({ ...item, x: insights.trend.length === 1 ? 53 : 8 + index / (insights.trend.length - 1) * 88, y: 25 - item.leftoverKg / max * 15 })); return { max, points, total: insights.trend.reduce((sum, item) => sum + item.leftoverKg, 0), average: insights.trend.length ? insights.trend.reduce((sum, item) => sum + item.leftoverKg, 0) / insights.trend.length : 0 }; }, [insights.trend]);
  const points = chart.points;
  const path = points.map((point, index) => `${index ? 'L' : 'M'} ${point.x} ${point.y}`).join(' ');
  const areaPath = points.length ? `M ${points[0].x} 27 ${points.map((point) => `L ${point.x} ${point.y}`).join(' ')} L ${points.at(-1)!.x} 27 Z` : '';
  const tickValues = [chart.max, chart.max / 2, 0];
  const dateLabel = (value: string) => new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short' }).format(new Date(`${value}T12:00:00`));
  return <section className="producer-panel producer-insights">
    <header><div><p className="eyebrow">30-day view</p><h2>Waste patterns</h2></div><TrendingDown size={18} /></header>
    {insights.totalLogs ? <>
      <div className="ops-trend"><div className="ops-trend__heading"><div><span>Leftover food by service</span><small>{insights.totalLogs} record{insights.totalLogs === 1 ? '' : 's'} across 30 days</small></div><strong>{chart.total.toFixed(1)} kg total</strong></div>{points.length > 1 ? <><div className="trend-callouts"><span><b>{points.at(-1)!.leftoverKg} kg</b> latest</span><span><b>{chart.average.toFixed(1)} kg</b> average</span><span><b>{chart.max} kg</b> peak</span></div><div className="ops-trend__chart"><div className="trend-y-labels" aria-hidden="true">{tickValues.map((value) => <span key={value}>{value.toFixed(value % 1 ? 1 : 0)} kg</span>)}</div><svg viewBox="0 0 100 30" preserveAspectRatio="none" role="img" aria-label="Thirty day waste trend"><defs><linearGradient id="trend-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="currentColor" stopOpacity=".22" /><stop offset="100%" stopColor="currentColor" stopOpacity="0" /></linearGradient></defs>{tickValues.map((value, index) => <line key={value} x1="8" x2="96" y1={index === 0 ? 6 : index === 1 ? 15 : 27} y2={index === 0 ? 6 : index === 1 ? 15 : 27} className="trend-gridline" />)}<path d={areaPath} className="trend-area" /> <path d={path} className="trend-line" />{points.map((point) => <g key={`${point.date}-${point.x}`}><title>{`${dateLabel(point.date)}: ${point.leftoverKg} kg`}</title><circle cx={point.x} cy={point.y} r=".85" /></g>)}</svg></div><div className="trend-x-labels" style={{ gridTemplateColumns: `repeat(${points.length}, minmax(0, 1fr))` }} aria-hidden="true">{points.map((point) => <span key={point.date}>{dateLabel(point.date)}</span>)}</div></> : <p className="chart-placeholder">Add another dated record to draw a trend.</p>}</div>
      <Breakdown title="Where waste occurs" rows={insights.stageBreakdown.map((item) => ({ label: stageLabels[item.stage], value: item.wasteKg }))} />
      <Breakdown title="By service period" rows={insights.serviceBreakdown.map((item) => ({ label: serviceLabels[item.servicePeriod], value: item.wasteKg }))} />
      {insights.categoryBreakdown.length > 0 && <Breakdown title="Food categories" rows={insights.categoryBreakdown.map((item) => ({ label: item.category, value: item.wasteKg }))} />}
      <div className="guidance"><Lightbulb size={19} /><div><strong>Reduction guidance</strong>{insights.guidance.length ? insights.guidance.map((item) => <p key={item}>{item}</p>) : <p>Record at least three services to identify a reliable concentration of waste.</p>}</div></div>
    </> : <div className="producer-empty"><span><TrendingDown size={22} /></span><h3>Insights begin with measured waste.</h3><p>After a few records, Bloom will show patterns without inventing forecasts.</p></div>}
  </section>;
}

function Breakdown({ title, rows }: { title: string; rows: Array<{ label: string; value: number }> }) { const max = Math.max(...rows.map((row) => row.value), 1); return <div className="ops-breakdown"><h3>{title}</h3>{rows.length ? rows.slice(0, 5).map((row) => <div key={row.label}><span>{row.label}</span><strong>{row.value} kg</strong><i><b style={{ width: `${row.value / max * 100}%` }} /></i></div>) : <p>No classified records yet.</p>}</div>; }

function PublishPickupDialog({ log, onClose, onPublished }: { log: DailyWasteLog | null; onClose: () => void; onPublished: () => Promise<void> }) {
  const [availableFrom, setAvailableFrom] = useState(localDateTime()); const [pickupDeadline, setPickupDeadline] = useState(localDateTime(new Date(Date.now() + 2 * 60 * 60 * 1000))); const [instructions, setInstructions] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (log) { setAvailableFrom(localDateTime()); setPickupDeadline(localDateTime(new Date(Date.now() + 2 * 60 * 60 * 1000))); setInstructions(''); setError(''); } }, [log]);
  if (!log) return null;
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await api(`/waste-logs/${log.id}/publish-pickup`, { method: 'POST', body: JSON.stringify({ eligibleRoles: ['FOOD_COLLECTOR'], availableFrom: new Date(availableFrom).toISOString(), pickupDeadline: new Date(pickupDeadline).toISOString(), instructions }) }); await onPublished(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'The pickup could not be published.'); } finally { setBusy(false); } };
  return <div className="dialog-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) onClose(); }}><form className="dialog publish-pickup-dialog" role="dialog" aria-modal="true" aria-labelledby="publish-title" onSubmit={submit}><p className="eyebrow">Offer {log.leftoverKg} kg</p><h2 id="publish-title">Publish for collection</h2><p>Verified Food Collectors will see the saved collection address and this collection window.</p>{error && <Notice tone="error">{error}</Notice>}<div className="field-grid"><Field label="Collection starts"><input type="datetime-local" value={availableFrom} onChange={(event) => setAvailableFrom(event.target.value)} required /></Field><Field label="Collection deadline"><input type="datetime-local" value={pickupDeadline} min={availableFrom} onChange={(event) => setPickupDeadline(event.target.value)} required /></Field></div><Field label="Pickup instructions (optional)"><textarea rows={3} maxLength={400} value={instructions} onChange={(event) => setInstructions(event.target.value)} /></Field><div className="form-actions"><button type="button" className="button button--quiet" onClick={onClose}>Keep as record</button><button className="button button--primary" disabled={busy}>{busy ? 'Publishing…' : 'Publish pickup'}</button></div></form></div>;
}
