import { CalendarPlus, ChevronLeft, ChevronRight, Plus, Search, Trash2, Utensils } from 'lucide-react';
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import type { Meal, MealAssignment, RecurrenceRule } from '@bloom/contracts';
import { api, formatDate, today } from '../api';
import { ConfirmDialog, DatePicker, Field, MealCombobox, Notice, SelectField, Spinner } from '../components';

const monthName = (date: Date) => new Intl.DateTimeFormat('en-IN', { month: 'long', year: 'numeric' }).format(date);
const iso = (date: Date) => new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 10);
const parseIsoDate = (value: string) => new Date(`${value}T00:00:00`);

export function MealCalendar() {
  const [meals, setMeals] = useState<Meal[]>([]); const [assignments, setAssignments] = useState<MealAssignment[]>([]); const [month, setMonth] = useState(() => new Date());
  const [selectedDate, setSelectedDate] = useState(today()); const [selectedMeals, setSelectedMeals] = useState<string[]>([]); const [frequency, setFrequency] = useState<RecurrenceRule['frequency']>('NONE'); const [endDate, setEndDate] = useState('');
  const [mealName, setMealName] = useState(''); const [query, setQuery] = useState(''); const [mealToDelete, setMealToDelete] = useState<Meal | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = async () => { setLoading(true); try { const [m, a] = await Promise.all([api<{ data: Meal[] }>('/meals'), api<{ data: MealAssignment[] }>('/meal-assignments')]); setMeals(m.data); setAssignments(a.data); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Meal calendar could not be loaded.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  useEffect(() => { const existing = assignments.find((item) => item.date === selectedDate); setSelectedMeals(existing?.mealIds ?? []); setFrequency('NONE'); setEndDate(''); }, [selectedDate, assignments]);
  const createMeal = async (event: FormEvent) => { event.preventDefault(); if (!mealName.trim()) return; setBusy(true); setError(''); try { await api('/meals', { method: 'POST', body: JSON.stringify({ name: mealName }) }); setMealName(''); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'The meal could not be added.'); } finally { setBusy(false); } };
  const deleteMeal = async () => { if (!mealToDelete) return; setBusy(true); setError(''); try { await api(`/meals/${mealToDelete.id}`, { method: 'DELETE' }); setMealToDelete(null); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'The meal could not be deleted.'); } finally { setBusy(false); } };
  const saveAssignment = async () => { if (!selectedMeals.length) { setError('Choose at least one meal for this date.'); return; } setBusy(true); setError(''); try { await api('/meal-assignments', { method: 'POST', body: JSON.stringify({ date: selectedDate, mealIds: selectedMeals, recurrence: { frequency, ...(frequency !== 'NONE' && endDate ? { endDate } : {}) } }) }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'The schedule could not be saved.'); } finally { setBusy(false); } };
  const calendarDays = useMemo(() => {
    const year = month.getFullYear(), monthIndex = month.getMonth(); const first = new Date(year, monthIndex, 1); const start = new Date(year, monthIndex, 1 - first.getDay());
    return Array.from({ length: 42 }, (_, index) => { const date = new Date(start); date.setDate(start.getDate() + index); return date; });
  }, [month]);
  const filteredMeals = meals.filter((meal) => meal.name.toLowerCase().includes(query.toLowerCase()));
  if (loading) return <main className="page"><Spinner label="Opening your meal calendar" /></main>;
  return <main className="page calendar-page">
    <section className="page-heading"><div><p className="eyebrow">Kitchen planning</p><h1>Meal calendar</h1><p>Build a clean meal library, then schedule single dates or repeating routines.</p></div></section>
    {error && <Notice tone="error">{error}</Notice>}
    <div className="planner-layout">
      <div className="planner-top">
      <section className="meal-library"><div className="panel-title"><div><p className="eyebrow">Library</p><h2>Your meals</h2><p>Keep a reusable collection of dishes for quick scheduling.</p></div><span>{meals.length} meals</span></div><form onSubmit={createMeal} className="add-meal"><Field label="Add a meal"><span><input value={mealName} onChange={(e) => setMealName(e.target.value)} placeholder="e.g. Tomato rice" /><button disabled={busy} aria-label="Add meal"><Plus size={17} /></button></span></Field></form><label className="library-search"><Search size={16} /><span className="sr-only">Search meal library</span><input placeholder="Search your meals" value={query} onChange={(e) => setQuery(e.target.value)} /></label><div className="meal-list">{filteredMeals.map((meal) => <article key={meal.id}><span><Utensils size={16} /></span><p>{meal.name}</p><button onClick={() => setMealToDelete(meal)} aria-label={`Delete ${meal.name}`}><Trash2 size={15} /></button></article>)}{!filteredMeals.length && <div className="mini-empty"><p>No meals match this search.</p></div>}</div></section>
      <aside className="schedule-editor"><div className="panel-title"><div><p className="eyebrow">Schedule</p><h2>{formatDate(selectedDate, { weekday: 'long', day: 'numeric', month: 'short' })}</h2><p>Choose a date, assign meals, and add an optional routine.</p></div><CalendarPlus size={20} /></div><DatePicker label="Service date" value={selectedDate} onChange={(value) => { setSelectedDate(value); setMonth(parseIsoDate(value)); }} /><Field label="Meals"><MealCombobox meals={meals} selected={selectedMeals} onChange={setSelectedMeals} /></Field><Field label="Repeat"><SelectField value={frequency} onChange={(e) => setFrequency(e.target.value as RecurrenceRule['frequency'])}><option value="NONE">Does not repeat</option><option value="WEEKLY">Every week</option><option value="BIWEEKLY">Every two weeks</option></SelectField></Field>{frequency !== 'NONE' && <DatePicker label="Repeat until" value={endDate} min={selectedDate} allowClear onChange={setEndDate} />}<button className="button button--primary button--wide" onClick={saveAssignment} disabled={busy || !selectedMeals.length}>{busy ? 'Saving schedule' : frequency === 'NONE' ? 'Save this date' : 'Save repeating schedule'}</button><p className="editor-note">Repeating schedules create individual dated entries, so each service can still be adjusted later.</p></aside>
      </div>
      <section className="calendar-workspace">
        <div className="calendar-section-heading"><div><p className="eyebrow">Calendar</p><h2>Monthly schedule</h2></div><p>Select any day to review or change its meals.</p></div>
        <div className="calendar-toolbar"><button className="icon-button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))} aria-label="Previous month"><ChevronLeft size={19} /></button><h2>{monthName(month)}</h2><button className="icon-button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))} aria-label="Next month"><ChevronRight size={19} /></button><button className="button button--quiet" onClick={() => { const now = new Date(); setMonth(now); setSelectedDate(today()); }}>Today</button></div>
        <div className="calendar-weekdays" aria-hidden="true">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((day) => <span key={day}>{day}</span>)}</div>
        <div className="calendar-grid">{calendarDays.map((date) => { const value = iso(date); const assignment = assignments.find((item) => item.date === value); const names = assignment?.mealIds.map((id) => meals.find((meal) => meal.id === id)?.name).filter(Boolean) ?? []; return <button key={value} className={`${date.getMonth() !== month.getMonth() ? 'outside ' : ''}${selectedDate === value ? 'selected ' : ''}${value === today() ? 'today' : ''}`} onClick={() => setSelectedDate(value)} aria-label={`${formatDate(value)}, ${names.length ? names.join(', ') : 'no meals scheduled'}`}><time>{date.getDate()}</time>{names.slice(0, 2).map((name) => <span key={name}>{name}</span>)}{names.length > 2 && <small>+{names.length - 2} more</small>}</button>; })}</div>
      </section>
    </div><ConfirmDialog open={Boolean(mealToDelete)} title={`Delete “${mealToDelete?.name ?? ''}”?`} description="This removes the meal from the library and future calendar assignments. Historical waste logs keep their original record." confirmLabel="Delete meal" busy={busy} onConfirm={deleteMeal} onCancel={() => setMealToDelete(null)} />
  </main>;
}
