import { ArrowRight, CheckCircle2, Clock3, PackageOpen, Truck } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { Pickup, PickupStatus } from '@bloom/contracts';
import { api } from '../api';
import { ConfirmDialog, Notice, Spinner } from '../components';

const labels: Record<PickupStatus, string> = { AVAILABLE: 'Waiting for a partner', RESERVED: 'Reserved', IN_TRANSIT: 'Partner in transit', AWAITING_PROVIDER_CONFIRMATION: 'Confirm collection', COLLECTED: 'Collected', CANCELLED: 'Cancelled', EXPIRED: 'Expired' };
const steps: PickupStatus[] = ['AVAILABLE', 'RESERVED', 'IN_TRANSIT', 'AWAITING_PROVIDER_CONFIRMATION', 'COLLECTED'];
const routeLabel = (pickup: Pickup) => pickup.eligibleRoles.length === 2 ? 'Farmer / Collector or Composter' : pickup.eligibleRoles[0] === 'COMPOSTER' ? 'Composter' : 'Farmer / Collector';

export function Pickups() {
  const [pickups, setPickups] = useState<Pickup[] | null>(null); const [confirming, setConfirming] = useState<Pickup | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = () => { setError(''); api<{ data: Pickup[] }>('/pickups').then((body) => setPickups(body.data)).catch((reason) => setError(reason.message)); };
  useEffect(load, []);
  const confirm = async () => { if (!confirming) return; setBusy(true); try { await api(`/pickups/${confirming.id}/confirm`, { method: 'POST' }); setConfirming(null); load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Collection could not be confirmed.'); } finally { setBusy(false); } };
  const active = pickups?.filter((item) => !['COLLECTED', 'CANCELLED', 'EXPIRED'].includes(item.status)) ?? []; const history = pickups?.filter((item) => ['COLLECTED', 'CANCELLED', 'EXPIRED'].includes(item.status)) ?? [];
  return <main className="page pickups-page"><section className="page-heading"><div><p className="eyebrow">Recovery</p><h1>Food recovery pickups</h1><p>See what is waiting, who is moving, and what has been collected.</p></div></section>{error && <Notice tone="error"><span>{error}</span><button onClick={load}>Try again</button></Notice>}{!pickups ? <Spinner label="Loading pickups" /> : <><section className="pickup-section"><div className="simple-heading"><h2>Active</h2><span>{active.length}</span></div>{active.length ? <div className="pickup-list">{active.map((pickup) => { const current = steps.indexOf(pickup.status); return <article className="pickup-card" key={pickup.id}><div className="pickup-card__top"><span className="pickup-icon"><Truck size={20} /></span><div><small>{labels[pickup.status]}</small><h3>{pickup.estimatedWeightKg} kg recovery pickup</h3><p>{routeLabel(pickup)} · Deadline {new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', hour: 'numeric', minute: '2-digit' }).format(new Date(pickup.pickupDeadline))}</p>{pickup.reservedByName && <p>Recovery partner: {pickup.reservedByName}</p>}</div>{pickup.status === 'AWAITING_PROVIDER_CONFIRMATION' && <button className="button button--primary" onClick={() => setConfirming(pickup)}>Confirm collection<ArrowRight size={16} /></button>}</div><ol className="pickup-progress">{steps.map((step, index) => <li className={index <= current ? 'complete' : ''} key={step}><i>{index < current ? <CheckCircle2 size={15} /> : <Clock3 size={14} />}</i><span>{labels[step]}</span></li>)}</ol></article>; })}</div> : <div className="empty-state empty-state--compact"><span><PackageOpen size={23} /></span><h3>No active pickups</h3><p>Mark a service record as suitable for collection, then publish it from the waste tracker.</p></div>}</section><section className="pickup-section"><div className="simple-heading"><h2>Recent history</h2><span>{history.length}</span></div>{history.length ? <div className="history-table">{history.map((pickup) => <article key={pickup.id}><span><CheckCircle2 size={17} /></span><div><strong>{pickup.estimatedWeightKg} kg</strong><small>{labels[pickup.status]} · {routeLabel(pickup)}</small></div><time>{new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(pickup.updatedAt))}</time></article>)}</div> : <p className="muted-copy">Confirmed pickups will appear here.</p>}</section></>}<ConfirmDialog open={Boolean(confirming)} title={`Confirm ${confirming?.estimatedWeightKg ?? ''} kg was collected?`} description="This closes the pickup as Collected and permanently locks its linked waste record." confirmLabel="Confirm collection" tone="primary" busy={busy} onConfirm={confirm} onCancel={() => setConfirming(null)} /></main>;
}
